/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.jonminter.distributedmergesort;

import java.io.IOException;
import org.junit.Test;

public class DistMergeSortServerTest {
    @Test public void testAppHasAGreeting() throws IOException {

    }
}
